/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 *
 * @author Gustavo Patiño Salas
 */
public class frmConfiguracionCultivos extends javax.swing.JFrame {

    private Apariencia util = new Apariencia();
    /**
     * Creates new form frmConfiguracionCultivos
     */
    public frmConfiguracionCultivos() {
        initComponents();
        this.setSize(550, 600);
        util.cambiarApariencia(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnRefrescar = new javax.swing.JButton();
        pnlNombre = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JTextField();
        pnlDatosIdeales = new javax.swing.JPanel();
        lblProtocolo = new javax.swing.JLabel();
        jcbSistemaRiego = new javax.swing.JComboBox();
        pnlDesarrollo = new javax.swing.JPanel();
        lblDiasDesarrollo = new javax.swing.JLabel();
        txtDesarrollo = new javax.swing.JTextField();
        lblHumedadSDesarrollo = new javax.swing.JLabel();
        txtHumedadSDesarrollo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblTemperaturaDesarrollo = new javax.swing.JLabel();
        txtTemperaturaDesarrollo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblHumedadRDesarrollo = new javax.swing.JLabel();
        txtHumedadRDesarrollo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblPHDesarrollo = new javax.swing.JLabel();
        txtPHDesarrollo = new javax.swing.JTextField();
        pnlFloracion = new javax.swing.JPanel();
        lblDiasFloracion = new javax.swing.JLabel();
        txtDiasFloracion = new javax.swing.JTextField();
        lblHumedadSFolracion = new javax.swing.JLabel();
        txtHumedadSFolracion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblTemperaturaFolracion = new javax.swing.JLabel();
        txtTemperaturaFolracion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblHumedadRFolracion = new javax.swing.JLabel();
        txtHumedadRFolracion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblPHFloracion = new javax.swing.JLabel();
        txtPHFloracion = new javax.swing.JTextField();
        pnlFructificacion = new javax.swing.JPanel();
        lblDiasFructificacion = new javax.swing.JLabel();
        txtDesarrollo4 = new javax.swing.JTextField();
        lblHumedadSFructificacion = new javax.swing.JLabel();
        txtHumedadSFructificacion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lblTemperaturaFructificacion = new javax.swing.JLabel();
        txtTemperaturaFructificacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lblHumedadRFructificacion = new javax.swing.JLabel();
        txtHumedadRFructificacion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lblPHFructificacion = new javax.swing.JLabel();
        txtPHFructificacion = new javax.swing.JTextField();
        pnlTablaCultivos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 500));
        setMinimumSize(new java.awt.Dimension(550, 500));
        setPreferredSize(new java.awt.Dimension(550, 500));
        setResizable(false);

        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(400, 30));

        btnAgregar.setText("jButton1");
        btnAgregar.setFocusable(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnAgregar);

        btnEditar.setText("jButton2");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEditar);

        btnEliminar.setText("jButton3");
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEliminar);
        jToolBar1.add(jSeparator1);

        btnCancelar.setText("jButton4");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCancelar);

        btnAceptar.setText("jButton5");
        btnAceptar.setFocusable(false);
        btnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnAceptar);
        jToolBar1.add(jSeparator2);

        btnRefrescar.setText("jButton6");
        btnRefrescar.setFocusable(false);
        btnRefrescar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefrescar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnRefrescar);

        pnlNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setMaximumSize(new java.awt.Dimension(200, 20));
        txtNombre.setMinimumSize(new java.awt.Dimension(200, 20));
        txtNombre.setName(""); // NOI18N
        txtNombre.setPreferredSize(new java.awt.Dimension(200, 20));

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre Cultivo:");
        lblNombre.setMaximumSize(new java.awt.Dimension(100, 20));
        lblNombre.setMinimumSize(new java.awt.Dimension(100, 20));
        lblNombre.setPreferredSize(new java.awt.Dimension(100, 20));

        lblTiempo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTiempo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTiempo.setText("Tiempo en dias:");
        lblTiempo.setMaximumSize(new java.awt.Dimension(100, 20));
        lblTiempo.setMinimumSize(new java.awt.Dimension(100, 20));
        lblTiempo.setPreferredSize(new java.awt.Dimension(100, 20));

        txtTiempo.setMaximumSize(new java.awt.Dimension(40, 20));
        txtTiempo.setMinimumSize(new java.awt.Dimension(40, 20));
        txtTiempo.setPreferredSize(new java.awt.Dimension(40, 20));

        javax.swing.GroupLayout pnlNombreLayout = new javax.swing.GroupLayout(pnlNombre);
        pnlNombre.setLayout(pnlNombreLayout);
        pnlNombreLayout.setHorizontalGroup(
            pnlNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNombreLayout.setVerticalGroup(
            pnlNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatosIdeales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Requerimientos del Cultivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lblProtocolo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblProtocolo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProtocolo.setText("Sistema de Riego:");
        lblProtocolo.setMaximumSize(new java.awt.Dimension(115, 14));
        lblProtocolo.setMinimumSize(new java.awt.Dimension(115, 14));
        lblProtocolo.setPreferredSize(new java.awt.Dimension(115, 14));

        jcbSistemaRiego.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        pnlDesarrollo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Desarrollo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lblDiasDesarrollo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDiasDesarrollo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiasDesarrollo.setText("Dias:");
        lblDiasDesarrollo.setMaximumSize(new java.awt.Dimension(40, 20));
        lblDiasDesarrollo.setMinimumSize(new java.awt.Dimension(40, 20));
        lblDiasDesarrollo.setPreferredSize(new java.awt.Dimension(40, 20));

        txtDesarrollo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDesarrollo.setMaximumSize(new java.awt.Dimension(30, 20));
        txtDesarrollo.setMinimumSize(new java.awt.Dimension(30, 20));
        txtDesarrollo.setPreferredSize(new java.awt.Dimension(30, 20));

        lblHumedadSDesarrollo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHumedadSDesarrollo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHumedadSDesarrollo.setText("Humedad Suelo:");
        lblHumedadSDesarrollo.setMaximumSize(new java.awt.Dimension(100, 20));
        lblHumedadSDesarrollo.setMinimumSize(new java.awt.Dimension(100, 20));
        lblHumedadSDesarrollo.setPreferredSize(new java.awt.Dimension(100, 20));

        txtHumedadSDesarrollo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHumedadSDesarrollo.setMaximumSize(new java.awt.Dimension(30, 20));
        txtHumedadSDesarrollo.setMinimumSize(new java.awt.Dimension(30, 20));
        txtHumedadSDesarrollo.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("%");

        lblTemperaturaDesarrollo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTemperaturaDesarrollo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTemperaturaDesarrollo.setText("Temperatura:");
        lblTemperaturaDesarrollo.setMaximumSize(new java.awt.Dimension(100, 20));
        lblTemperaturaDesarrollo.setMinimumSize(new java.awt.Dimension(100, 20));
        lblTemperaturaDesarrollo.setPreferredSize(new java.awt.Dimension(100, 20));

        txtTemperaturaDesarrollo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTemperaturaDesarrollo.setMaximumSize(new java.awt.Dimension(30, 20));
        txtTemperaturaDesarrollo.setMinimumSize(new java.awt.Dimension(30, 20));
        txtTemperaturaDesarrollo.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("°C");

        lblHumedadRDesarrollo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHumedadRDesarrollo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHumedadRDesarrollo.setText("Humedad Relativa:");
        lblHumedadRDesarrollo.setMaximumSize(new java.awt.Dimension(115, 20));
        lblHumedadRDesarrollo.setMinimumSize(new java.awt.Dimension(115, 20));
        lblHumedadRDesarrollo.setPreferredSize(new java.awt.Dimension(115, 20));

        txtHumedadRDesarrollo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHumedadRDesarrollo.setMaximumSize(new java.awt.Dimension(30, 20));
        txtHumedadRDesarrollo.setMinimumSize(new java.awt.Dimension(30, 20));
        txtHumedadRDesarrollo.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("%");

        lblPHDesarrollo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPHDesarrollo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPHDesarrollo.setText("PH:");
        lblPHDesarrollo.setMaximumSize(new java.awt.Dimension(30, 20));
        lblPHDesarrollo.setMinimumSize(new java.awt.Dimension(30, 20));
        lblPHDesarrollo.setPreferredSize(new java.awt.Dimension(30, 20));

        txtPHDesarrollo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPHDesarrollo.setMaximumSize(new java.awt.Dimension(30, 20));
        txtPHDesarrollo.setMinimumSize(new java.awt.Dimension(30, 20));
        txtPHDesarrollo.setPreferredSize(new java.awt.Dimension(30, 20));

        javax.swing.GroupLayout pnlDesarrolloLayout = new javax.swing.GroupLayout(pnlDesarrollo);
        pnlDesarrollo.setLayout(pnlDesarrolloLayout);
        pnlDesarrolloLayout.setHorizontalGroup(
            pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDesarrolloLayout.createSequentialGroup()
                .addGroup(pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHumedadRDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDesarrolloLayout.createSequentialGroup()
                        .addComponent(lblDiasDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHumedadSDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDesarrolloLayout.createSequentialGroup()
                        .addComponent(txtHumedadSDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblTemperaturaDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTemperaturaDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(pnlDesarrolloLayout.createSequentialGroup()
                        .addComponent(txtHumedadRDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblPHDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPHDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDesarrolloLayout.setVerticalGroup(
            pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDesarrolloLayout.createSequentialGroup()
                .addGroup(pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiasDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHumedadSDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHumedadSDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lblTemperaturaDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperaturaDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHumedadRDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHumedadRDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(lblPHDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPHDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFloracion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Floracion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lblDiasFloracion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDiasFloracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiasFloracion.setText("Dias:");
        lblDiasFloracion.setMaximumSize(new java.awt.Dimension(40, 20));
        lblDiasFloracion.setMinimumSize(new java.awt.Dimension(40, 20));
        lblDiasFloracion.setPreferredSize(new java.awt.Dimension(40, 20));

        txtDiasFloracion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDiasFloracion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtDiasFloracion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtDiasFloracion.setPreferredSize(new java.awt.Dimension(30, 20));

        lblHumedadSFolracion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHumedadSFolracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHumedadSFolracion.setText("Humedad Suelo:");
        lblHumedadSFolracion.setMaximumSize(new java.awt.Dimension(100, 20));
        lblHumedadSFolracion.setMinimumSize(new java.awt.Dimension(100, 20));
        lblHumedadSFolracion.setPreferredSize(new java.awt.Dimension(100, 20));

        txtHumedadSFolracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHumedadSFolracion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtHumedadSFolracion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtHumedadSFolracion.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("%");

        lblTemperaturaFolracion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTemperaturaFolracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTemperaturaFolracion.setText("Temperatura:");
        lblTemperaturaFolracion.setMaximumSize(new java.awt.Dimension(100, 20));
        lblTemperaturaFolracion.setMinimumSize(new java.awt.Dimension(100, 20));
        lblTemperaturaFolracion.setPreferredSize(new java.awt.Dimension(100, 20));

        txtTemperaturaFolracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTemperaturaFolracion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtTemperaturaFolracion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtTemperaturaFolracion.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("°C");

        lblHumedadRFolracion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHumedadRFolracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHumedadRFolracion.setText("Humedad Relativa:");
        lblHumedadRFolracion.setMaximumSize(new java.awt.Dimension(115, 20));
        lblHumedadRFolracion.setMinimumSize(new java.awt.Dimension(115, 20));
        lblHumedadRFolracion.setPreferredSize(new java.awt.Dimension(115, 20));

        txtHumedadRFolracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHumedadRFolracion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtHumedadRFolracion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtHumedadRFolracion.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("%");

        lblPHFloracion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPHFloracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPHFloracion.setText("PH:");
        lblPHFloracion.setMaximumSize(new java.awt.Dimension(30, 20));
        lblPHFloracion.setMinimumSize(new java.awt.Dimension(30, 20));
        lblPHFloracion.setPreferredSize(new java.awt.Dimension(30, 20));

        txtPHFloracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPHFloracion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtPHFloracion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtPHFloracion.setPreferredSize(new java.awt.Dimension(30, 20));

        javax.swing.GroupLayout pnlFloracionLayout = new javax.swing.GroupLayout(pnlFloracion);
        pnlFloracion.setLayout(pnlFloracionLayout);
        pnlFloracionLayout.setHorizontalGroup(
            pnlFloracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFloracionLayout.createSequentialGroup()
                .addGroup(pnlFloracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHumedadRFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFloracionLayout.createSequentialGroup()
                        .addComponent(lblDiasFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiasFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHumedadSFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFloracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFloracionLayout.createSequentialGroup()
                        .addComponent(txtHumedadSFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lblTemperaturaFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTemperaturaFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(pnlFloracionLayout.createSequentialGroup()
                        .addComponent(txtHumedadRFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lblPHFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPHFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFloracionLayout.setVerticalGroup(
            pnlFloracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFloracionLayout.createSequentialGroup()
                .addGroup(pnlFloracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiasFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiasFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHumedadSFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHumedadSFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(lblTemperaturaFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperaturaFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(pnlFloracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHumedadRFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHumedadRFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(lblPHFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPHFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFructificacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fructificacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lblDiasFructificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDiasFructificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiasFructificacion.setText("Dias:");
        lblDiasFructificacion.setMaximumSize(new java.awt.Dimension(40, 20));
        lblDiasFructificacion.setMinimumSize(new java.awt.Dimension(40, 20));
        lblDiasFructificacion.setPreferredSize(new java.awt.Dimension(40, 20));

        txtDesarrollo4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDesarrollo4.setMaximumSize(new java.awt.Dimension(30, 20));
        txtDesarrollo4.setMinimumSize(new java.awt.Dimension(30, 20));
        txtDesarrollo4.setPreferredSize(new java.awt.Dimension(30, 20));

        lblHumedadSFructificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHumedadSFructificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHumedadSFructificacion.setText("Humedad Suelo:");
        lblHumedadSFructificacion.setMaximumSize(new java.awt.Dimension(100, 20));
        lblHumedadSFructificacion.setMinimumSize(new java.awt.Dimension(100, 20));
        lblHumedadSFructificacion.setPreferredSize(new java.awt.Dimension(100, 20));

        txtHumedadSFructificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHumedadSFructificacion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtHumedadSFructificacion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtHumedadSFructificacion.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("%");

        lblTemperaturaFructificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTemperaturaFructificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTemperaturaFructificacion.setText("Temperatura:");
        lblTemperaturaFructificacion.setMaximumSize(new java.awt.Dimension(100, 20));
        lblTemperaturaFructificacion.setMinimumSize(new java.awt.Dimension(100, 20));
        lblTemperaturaFructificacion.setPreferredSize(new java.awt.Dimension(100, 20));

        txtTemperaturaFructificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTemperaturaFructificacion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtTemperaturaFructificacion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtTemperaturaFructificacion.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("°C");

        lblHumedadRFructificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHumedadRFructificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHumedadRFructificacion.setText("Humedad Relativa:");
        lblHumedadRFructificacion.setMaximumSize(new java.awt.Dimension(115, 20));
        lblHumedadRFructificacion.setMinimumSize(new java.awt.Dimension(115, 20));
        lblHumedadRFructificacion.setPreferredSize(new java.awt.Dimension(115, 20));

        txtHumedadRFructificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHumedadRFructificacion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtHumedadRFructificacion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtHumedadRFructificacion.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("%");

        lblPHFructificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPHFructificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPHFructificacion.setText("PH:");
        lblPHFructificacion.setMaximumSize(new java.awt.Dimension(30, 20));
        lblPHFructificacion.setMinimumSize(new java.awt.Dimension(30, 20));
        lblPHFructificacion.setPreferredSize(new java.awt.Dimension(30, 20));

        txtPHFructificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPHFructificacion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtPHFructificacion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtPHFructificacion.setPreferredSize(new java.awt.Dimension(30, 20));

        javax.swing.GroupLayout pnlFructificacionLayout = new javax.swing.GroupLayout(pnlFructificacion);
        pnlFructificacion.setLayout(pnlFructificacionLayout);
        pnlFructificacionLayout.setHorizontalGroup(
            pnlFructificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFructificacionLayout.createSequentialGroup()
                .addGroup(pnlFructificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHumedadRFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFructificacionLayout.createSequentialGroup()
                        .addComponent(lblDiasFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDesarrollo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHumedadSFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFructificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFructificacionLayout.createSequentialGroup()
                        .addComponent(txtHumedadSFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(lblTemperaturaFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTemperaturaFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(pnlFructificacionLayout.createSequentialGroup()
                        .addComponent(txtHumedadRFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(lblPHFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPHFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFructificacionLayout.setVerticalGroup(
            pnlFructificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFructificacionLayout.createSequentialGroup()
                .addGroup(pnlFructificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiasFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesarrollo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHumedadSFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHumedadSFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(lblTemperaturaFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperaturaFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(pnlFructificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHumedadRFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHumedadRFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(lblPHFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPHFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDatosIdealesLayout = new javax.swing.GroupLayout(pnlDatosIdeales);
        pnlDatosIdeales.setLayout(pnlDatosIdealesLayout);
        pnlDatosIdealesLayout.setHorizontalGroup(
            pnlDatosIdealesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosIdealesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosIdealesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDesarrollo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDatosIdealesLayout.createSequentialGroup()
                        .addComponent(lblProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbSistemaRiego, 0, 379, Short.MAX_VALUE))
                    .addComponent(pnlFloracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFructificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlDatosIdealesLayout.setVerticalGroup(
            pnlDatosIdealesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosIdealesLayout.createSequentialGroup()
                .addComponent(pnlDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDatosIdealesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbSistemaRiego)
                    .addComponent(lblProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlTablaCultivos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cultivos Existentes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        pnlTablaCultivos.setPreferredSize(new java.awt.Dimension(390, 197));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Humedad S", "Temperatura", "PH"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnlTablaCultivosLayout = new javax.swing.GroupLayout(pnlTablaCultivos);
        pnlTablaCultivos.setLayout(pnlTablaCultivosLayout);
        pnlTablaCultivosLayout.setHorizontalGroup(
            pnlTablaCultivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pnlTablaCultivosLayout.setVerticalGroup(
            pnlTablaCultivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDatosIdeales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTablaCultivos, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatosIdeales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTablaCultivos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConfiguracionCultivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConfiguracionCultivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConfiguracionCultivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConfiguracionCultivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConfiguracionCultivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox jcbSistemaRiego;
    private javax.swing.JLabel lblDiasDesarrollo;
    private javax.swing.JLabel lblDiasFloracion;
    private javax.swing.JLabel lblDiasFructificacion;
    private javax.swing.JLabel lblHumedadRDesarrollo;
    private javax.swing.JLabel lblHumedadRFolracion;
    private javax.swing.JLabel lblHumedadRFructificacion;
    private javax.swing.JLabel lblHumedadSDesarrollo;
    private javax.swing.JLabel lblHumedadSFolracion;
    private javax.swing.JLabel lblHumedadSFructificacion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPHDesarrollo;
    private javax.swing.JLabel lblPHFloracion;
    private javax.swing.JLabel lblPHFructificacion;
    private javax.swing.JLabel lblProtocolo;
    private javax.swing.JLabel lblTemperaturaDesarrollo;
    private javax.swing.JLabel lblTemperaturaFolracion;
    private javax.swing.JLabel lblTemperaturaFructificacion;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JPanel pnlDatosIdeales;
    private javax.swing.JPanel pnlDesarrollo;
    private javax.swing.JPanel pnlFloracion;
    private javax.swing.JPanel pnlFructificacion;
    private javax.swing.JPanel pnlNombre;
    private javax.swing.JPanel pnlTablaCultivos;
    private javax.swing.JTextField txtDesarrollo;
    private javax.swing.JTextField txtDesarrollo4;
    private javax.swing.JTextField txtDiasFloracion;
    private javax.swing.JTextField txtHumedadRDesarrollo;
    private javax.swing.JTextField txtHumedadRFolracion;
    private javax.swing.JTextField txtHumedadRFructificacion;
    private javax.swing.JTextField txtHumedadSDesarrollo;
    private javax.swing.JTextField txtHumedadSFolracion;
    private javax.swing.JTextField txtHumedadSFructificacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPHDesarrollo;
    private javax.swing.JTextField txtPHFloracion;
    private javax.swing.JTextField txtPHFructificacion;
    private javax.swing.JTextField txtTemperaturaDesarrollo;
    private javax.swing.JTextField txtTemperaturaFolracion;
    private javax.swing.JTextField txtTemperaturaFructificacion;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
