/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import VO.*;
import Controladores.ControlMenuPrincipal;

/**
 *
 * @author Gustavo Patiño Salas
 */
public class frmMenuPrincipal extends javax.swing.JFrame {
    
    //Obejto VO_Usuario con el que vamos a manipular los datos de usuario sin necesidad de ingresar en la base de datos.
    private VO_Usuario voUsuario;
    //Objeto frmMoniotoreoControl se usa para mantener un objeto de la clase y poderlo instanciar en cualquier momento.
    private frmMonitoreoControl frmMonitor;
    private frmDepositoAgua frmDeposito;
    private frmConfiguraciones frmConfiguracion;
    //OBjeto apariencias se usara para cambiar la apriencia visual de nuestra aplicacion.
    private Apariencia apariencia = new Apariencia();
    //El objeto ControlMenuPrincipal es que se usa para realizar las operaciones pricipales.
    private ControlMenuPrincipal control = new ControlMenuPrincipal();

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal(VO_Usuario voUsuario) {
        initComponents();
        this.voUsuario = voUsuario;
        this.apariencia.cambiarApariencia(this);
        this.control.activarOpciones(voUsuario, btnComtrol, btnInformes, btnDepositoAgua, btnConfiguracion);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnComtrol = new javax.swing.JButton();
        btnInformes = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        btnDepositoAgua = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmSalir = new javax.swing.JMenu();
        jmiCerrarSesion = new javax.swing.JMenuItem();
        jmiCerrarAplicacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnComtrol.setText("Monitoreo y control");
        btnComtrol.setMaximumSize(new java.awt.Dimension(150, 150));
        btnComtrol.setMinimumSize(new java.awt.Dimension(150, 150));
        btnComtrol.setPreferredSize(new java.awt.Dimension(150, 150));
        btnComtrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComtrolActionPerformed(evt);
            }
        });

        btnInformes.setText("Informes");
        btnInformes.setMaximumSize(new java.awt.Dimension(150, 150));
        btnInformes.setMinimumSize(new java.awt.Dimension(150, 150));
        btnInformes.setPreferredSize(new java.awt.Dimension(150, 150));

        btnConfiguracion.setText("Configuraciones");
        btnConfiguracion.setMaximumSize(new java.awt.Dimension(150, 150));
        btnConfiguracion.setMinimumSize(new java.awt.Dimension(150, 150));
        btnConfiguracion.setPreferredSize(new java.awt.Dimension(150, 150));
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });

        btnDepositoAgua.setText("Deposito de agua");
        btnDepositoAgua.setMaximumSize(new java.awt.Dimension(150, 150));
        btnDepositoAgua.setMinimumSize(new java.awt.Dimension(150, 150));
        btnDepositoAgua.setPreferredSize(new java.awt.Dimension(150, 150));

        jmSalir.setText("Salir");

        jmiCerrarSesion.setText("Cerrar Sesion");
        jmSalir.add(jmiCerrarSesion);

        jmiCerrarAplicacion.setText("Cerrar App");
        jmSalir.add(jmiCerrarAplicacion);

        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnComtrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInformes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDepositoAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInformes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComtrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepositoAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComtrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComtrolActionPerformed
        
        this.frmMonitor = new frmMonitoreoControl(this.voUsuario);
        this.frmMonitor.setVisible(true);
    }//GEN-LAST:event_btnComtrolActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        this.frmConfiguracion = new frmConfiguraciones(this.voUsuario);
        this.frmConfiguracion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComtrol;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnDepositoAgua;
    private javax.swing.JButton btnInformes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiCerrarAplicacion;
    private javax.swing.JMenuItem jmiCerrarSesion;
    // End of variables declaration//GEN-END:variables
}
