/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.awt.Dimension;
import VO.*;

/**
 *
 * @author Gustavo Patiño Salas
 */
public class frmMonitoreoControl extends javax.swing.JFrame {

    private Apariencia util = new Apariencia();
    //Obejto con el que manipularemos los datos del registro usuario sin necesidad de accerder a la base de datos.
    private VO_Usuario voUsuario;
    /**
     * Creates new form frmPrincipal1
     */
    public frmMonitoreoControl(VO_Usuario voUsuario) {
        initComponents();
        //this.ajustarFrame();
        this.setSize(1075, 630);
        util.cambiarApariencia(this);
        this.voUsuario = voUsuario;
        this.setTitle("SESION USUARIO: " + voUsuario.getUsu_nombres() + voUsuario.getUsu_apellidos());
    }

    // Metodo con el ajusto el tamaño de la ventana al tamaño de la pantalla.
    private void ajustarFrame(){
        //creo el objeto dimension y le asigno el tamaño del monitor.
        Dimension dim = this.getToolkit().getScreenSize();
        //ajusto las medidas para que salga correctamente.
        int alto = (int)dim.height - 40;
        int ancho = (int)dim.width;
        dim.setSize(ancho, alto);
        //asigno los valores respectivos.
        this.setMaximumSize(dim);
        this.setMinimumSize(dim);
        this.setPreferredSize(dim);
        this.pack();
        System.out.println("ancho = " + ancho + " alto = " + alto);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlCultivos = new javax.swing.JPanel();
        pnlDatosCultivo = new javax.swing.JPanel();
        lblNombreCult = new javax.swing.JLabel();
        txtNombreCult = new javax.swing.JTextField();
        lblNombreLote = new javax.swing.JLabel();
        txtNombreLote = new javax.swing.JTextField();
        lblNumProceso = new javax.swing.JLabel();
        txtNumProceso = new javax.swing.JTextField();
        lblDuracion = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        pnlDatosIdeales = new javax.swing.JPanel();
        pnlDesarrollo = new javax.swing.JPanel();
        lblDiasDesarrollo = new javax.swing.JLabel();
        txtDesarrollo = new javax.swing.JTextField();
        lblHumedadSDesarrollo = new javax.swing.JLabel();
        txtHumedadSDesarrollo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblTemperaturaDesarrollo = new javax.swing.JLabel();
        txtTemperaturaDesarrollo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblHumedadRDesarrollo = new javax.swing.JLabel();
        txtHumedadRDesarrollo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblPHDesarrollo = new javax.swing.JLabel();
        txtPHDesarrollo = new javax.swing.JTextField();
        pnlFloracion = new javax.swing.JPanel();
        lblDiasFloracion = new javax.swing.JLabel();
        txtDiasFloracion = new javax.swing.JTextField();
        lblHumedadSFolracion = new javax.swing.JLabel();
        txtHumedadSFolracion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblTemperaturaFolracion = new javax.swing.JLabel();
        txtTemperaturaFolracion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblHumedadRFolracion = new javax.swing.JLabel();
        txtHumedadRFolracion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblPHFloracion = new javax.swing.JLabel();
        txtPHFloracion = new javax.swing.JTextField();
        pnlFructificacion = new javax.swing.JPanel();
        lblDiasFructificacion = new javax.swing.JLabel();
        txtDesarrollo4 = new javax.swing.JTextField();
        lblHumedadSFructificacion = new javax.swing.JLabel();
        txtHumedadSFructificacion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lblTemperaturaFructificacion = new javax.swing.JLabel();
        txtTemperaturaFructificacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lblHumedadRFructificacion = new javax.swing.JLabel();
        txtHumedadRFructificacion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lblPHFructificacion = new javax.swing.JLabel();
        txtPHFructificacion = new javax.swing.JTextField();
        pnlDatosReales = new javax.swing.JPanel();
        lblEtapaCultivo = new javax.swing.JLabel();
        txtEtapaCultivo = new javax.swing.JTextField();
        lblDiasTranscurrido = new javax.swing.JLabel();
        txtDiasTranscurridos = new javax.swing.JTextField();
        lblHumedadSDesarrollo1 = new javax.swing.JLabel();
        txtHumedadSDesarrollo1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lblTemperaturaDesarrollo1 = new javax.swing.JLabel();
        txtTemperaturaDesarrollo1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPHDesarrollo1 = new javax.swing.JTextField();
        lblPHDesarrollo1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtHumedadRDesarrollo1 = new javax.swing.JTextField();
        lblHumedadRDesarrollo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1055, 591));
        setMinimumSize(new java.awt.Dimension(1055, 591));
        setPreferredSize(new java.awt.Dimension(1055, 591));
        setResizable(false);

        jToolBar1.setRollover(true);

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setText("jButton2");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        pnlDatosCultivo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Cultivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lblNombreCult.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombreCult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreCult.setText("Nombre Cultivo:");
        lblNombreCult.setMaximumSize(new java.awt.Dimension(100, 20));
        lblNombreCult.setMinimumSize(new java.awt.Dimension(100, 20));
        lblNombreCult.setPreferredSize(new java.awt.Dimension(100, 20));

        txtNombreCult.setEditable(false);
        txtNombreCult.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreCult.setMaximumSize(new java.awt.Dimension(200, 20));
        txtNombreCult.setMinimumSize(new java.awt.Dimension(200, 20));
        txtNombreCult.setName(""); // NOI18N
        txtNombreCult.setPreferredSize(new java.awt.Dimension(200, 20));

        lblNombreLote.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombreLote.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreLote.setText("Lote:");
        lblNombreLote.setMaximumSize(new java.awt.Dimension(50, 20));
        lblNombreLote.setMinimumSize(new java.awt.Dimension(50, 20));
        lblNombreLote.setPreferredSize(new java.awt.Dimension(50, 20));

        txtNombreLote.setEditable(false);
        txtNombreLote.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreLote.setMaximumSize(new java.awt.Dimension(200, 20));
        txtNombreLote.setMinimumSize(new java.awt.Dimension(200, 20));
        txtNombreLote.setName(""); // NOI18N
        txtNombreLote.setPreferredSize(new java.awt.Dimension(200, 20));
        txtNombreLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreLoteActionPerformed(evt);
            }
        });

        lblNumProceso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNumProceso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumProceso.setText("Proceso N°:");
        lblNumProceso.setMaximumSize(new java.awt.Dimension(70, 20));
        lblNumProceso.setMinimumSize(new java.awt.Dimension(70, 20));
        lblNumProceso.setPreferredSize(new java.awt.Dimension(70, 20));

        txtNumProceso.setEditable(false);
        txtNumProceso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumProceso.setMaximumSize(new java.awt.Dimension(50, 20));
        txtNumProceso.setMinimumSize(new java.awt.Dimension(50, 20));
        txtNumProceso.setName(""); // NOI18N
        txtNumProceso.setPreferredSize(new java.awt.Dimension(50, 20));
        txtNumProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumProcesoActionPerformed(evt);
            }
        });

        lblDuracion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDuracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDuracion.setText("Duracion en dias:");
        lblDuracion.setMaximumSize(new java.awt.Dimension(70, 20));
        lblDuracion.setMinimumSize(new java.awt.Dimension(70, 20));
        lblDuracion.setPreferredSize(new java.awt.Dimension(70, 20));

        txtDuracion.setEditable(false);
        txtDuracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDuracion.setMaximumSize(new java.awt.Dimension(50, 20));
        txtDuracion.setMinimumSize(new java.awt.Dimension(50, 20));
        txtDuracion.setName(""); // NOI18N
        txtDuracion.setPreferredSize(new java.awt.Dimension(50, 20));
        txtDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Fecha Inicio:");

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setMaximumSize(new java.awt.Dimension(100, 20));
        jTextField1.setMinimumSize(new java.awt.Dimension(100, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Fecha Fin Estimada:");

        jTextField2.setEditable(false);
        jTextField2.setMaximumSize(new java.awt.Dimension(100, 20));
        jTextField2.setMinimumSize(new java.awt.Dimension(100, 20));
        jTextField2.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Sistema de Riego:");

        jTextField3.setEditable(false);

        javax.swing.GroupLayout pnlDatosCultivoLayout = new javax.swing.GroupLayout(pnlDatosCultivo);
        pnlDatosCultivo.setLayout(pnlDatosCultivoLayout);
        pnlDatosCultivoLayout.setHorizontalGroup(
            pnlDatosCultivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCultivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosCultivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosCultivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlDatosCultivoLayout.createSequentialGroup()
                            .addComponent(lblNombreCult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNombreCult, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblNumProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNumProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlDatosCultivoLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlDatosCultivoLayout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField3)
                            .addGap(18, 18, 18)
                            .addComponent(lblDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDatosCultivoLayout.createSequentialGroup()
                        .addComponent(lblNombreLote, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosCultivoLayout.setVerticalGroup(
            pnlDatosCultivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCultivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosCultivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosCultivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosCultivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosCultivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatosIdeales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Requerimientos del Cultivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        pnlDesarrollo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Desarrollo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lblDiasDesarrollo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDiasDesarrollo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiasDesarrollo.setText("Dias:");
        lblDiasDesarrollo.setMaximumSize(new java.awt.Dimension(40, 20));
        lblDiasDesarrollo.setMinimumSize(new java.awt.Dimension(40, 20));
        lblDiasDesarrollo.setPreferredSize(new java.awt.Dimension(40, 20));

        txtDesarrollo.setEditable(false);
        txtDesarrollo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDesarrollo.setMaximumSize(new java.awt.Dimension(30, 20));
        txtDesarrollo.setMinimumSize(new java.awt.Dimension(30, 20));
        txtDesarrollo.setPreferredSize(new java.awt.Dimension(30, 20));

        lblHumedadSDesarrollo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHumedadSDesarrollo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHumedadSDesarrollo.setText("Humedad Suelo:");
        lblHumedadSDesarrollo.setMaximumSize(new java.awt.Dimension(100, 20));
        lblHumedadSDesarrollo.setMinimumSize(new java.awt.Dimension(100, 20));
        lblHumedadSDesarrollo.setPreferredSize(new java.awt.Dimension(100, 20));

        txtHumedadSDesarrollo.setEditable(false);
        txtHumedadSDesarrollo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHumedadSDesarrollo.setMaximumSize(new java.awt.Dimension(30, 20));
        txtHumedadSDesarrollo.setMinimumSize(new java.awt.Dimension(30, 20));
        txtHumedadSDesarrollo.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("%");

        lblTemperaturaDesarrollo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTemperaturaDesarrollo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTemperaturaDesarrollo.setText("Temperatura:");
        lblTemperaturaDesarrollo.setMaximumSize(new java.awt.Dimension(100, 20));
        lblTemperaturaDesarrollo.setMinimumSize(new java.awt.Dimension(100, 20));
        lblTemperaturaDesarrollo.setPreferredSize(new java.awt.Dimension(100, 20));

        txtTemperaturaDesarrollo.setEditable(false);
        txtTemperaturaDesarrollo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTemperaturaDesarrollo.setMaximumSize(new java.awt.Dimension(30, 20));
        txtTemperaturaDesarrollo.setMinimumSize(new java.awt.Dimension(30, 20));
        txtTemperaturaDesarrollo.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("°C");

        lblHumedadRDesarrollo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHumedadRDesarrollo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHumedadRDesarrollo.setText("Humedad Relativa:");
        lblHumedadRDesarrollo.setMaximumSize(new java.awt.Dimension(115, 20));
        lblHumedadRDesarrollo.setMinimumSize(new java.awt.Dimension(115, 20));
        lblHumedadRDesarrollo.setPreferredSize(new java.awt.Dimension(115, 20));

        txtHumedadRDesarrollo.setEditable(false);
        txtHumedadRDesarrollo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHumedadRDesarrollo.setMaximumSize(new java.awt.Dimension(30, 20));
        txtHumedadRDesarrollo.setMinimumSize(new java.awt.Dimension(30, 20));
        txtHumedadRDesarrollo.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("%");

        lblPHDesarrollo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPHDesarrollo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPHDesarrollo.setText("PH:");
        lblPHDesarrollo.setMaximumSize(new java.awt.Dimension(30, 20));
        lblPHDesarrollo.setMinimumSize(new java.awt.Dimension(30, 20));
        lblPHDesarrollo.setPreferredSize(new java.awt.Dimension(30, 20));

        txtPHDesarrollo.setEditable(false);
        txtPHDesarrollo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPHDesarrollo.setMaximumSize(new java.awt.Dimension(30, 20));
        txtPHDesarrollo.setMinimumSize(new java.awt.Dimension(30, 20));
        txtPHDesarrollo.setPreferredSize(new java.awt.Dimension(30, 20));

        javax.swing.GroupLayout pnlDesarrolloLayout = new javax.swing.GroupLayout(pnlDesarrollo);
        pnlDesarrollo.setLayout(pnlDesarrolloLayout);
        pnlDesarrolloLayout.setHorizontalGroup(
            pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDesarrolloLayout.createSequentialGroup()
                .addGroup(pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHumedadRDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDesarrolloLayout.createSequentialGroup()
                        .addComponent(lblDiasDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHumedadSDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDesarrolloLayout.createSequentialGroup()
                        .addComponent(txtHumedadSDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblTemperaturaDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTemperaturaDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(pnlDesarrolloLayout.createSequentialGroup()
                        .addComponent(txtHumedadRDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblPHDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPHDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDesarrolloLayout.setVerticalGroup(
            pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDesarrolloLayout.createSequentialGroup()
                .addGroup(pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiasDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHumedadSDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHumedadSDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lblTemperaturaDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperaturaDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHumedadRDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHumedadRDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(lblPHDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPHDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFloracion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Floracion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lblDiasFloracion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDiasFloracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiasFloracion.setText("Dias:");
        lblDiasFloracion.setMaximumSize(new java.awt.Dimension(40, 20));
        lblDiasFloracion.setMinimumSize(new java.awt.Dimension(40, 20));
        lblDiasFloracion.setPreferredSize(new java.awt.Dimension(40, 20));

        txtDiasFloracion.setEditable(false);
        txtDiasFloracion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDiasFloracion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtDiasFloracion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtDiasFloracion.setPreferredSize(new java.awt.Dimension(30, 20));

        lblHumedadSFolracion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHumedadSFolracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHumedadSFolracion.setText("Humedad Suelo:");
        lblHumedadSFolracion.setMaximumSize(new java.awt.Dimension(100, 20));
        lblHumedadSFolracion.setMinimumSize(new java.awt.Dimension(100, 20));
        lblHumedadSFolracion.setPreferredSize(new java.awt.Dimension(100, 20));

        txtHumedadSFolracion.setEditable(false);
        txtHumedadSFolracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHumedadSFolracion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtHumedadSFolracion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtHumedadSFolracion.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("%");

        lblTemperaturaFolracion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTemperaturaFolracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTemperaturaFolracion.setText("Temperatura:");
        lblTemperaturaFolracion.setMaximumSize(new java.awt.Dimension(100, 20));
        lblTemperaturaFolracion.setMinimumSize(new java.awt.Dimension(100, 20));
        lblTemperaturaFolracion.setPreferredSize(new java.awt.Dimension(100, 20));

        txtTemperaturaFolracion.setEditable(false);
        txtTemperaturaFolracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTemperaturaFolracion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtTemperaturaFolracion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtTemperaturaFolracion.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("°C");

        lblHumedadRFolracion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHumedadRFolracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHumedadRFolracion.setText("Humedad Relativa:");
        lblHumedadRFolracion.setMaximumSize(new java.awt.Dimension(115, 20));
        lblHumedadRFolracion.setMinimumSize(new java.awt.Dimension(115, 20));
        lblHumedadRFolracion.setPreferredSize(new java.awt.Dimension(115, 20));

        txtHumedadRFolracion.setEditable(false);
        txtHumedadRFolracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHumedadRFolracion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtHumedadRFolracion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtHumedadRFolracion.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("%");

        lblPHFloracion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPHFloracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPHFloracion.setText("PH:");
        lblPHFloracion.setMaximumSize(new java.awt.Dimension(30, 20));
        lblPHFloracion.setMinimumSize(new java.awt.Dimension(30, 20));
        lblPHFloracion.setPreferredSize(new java.awt.Dimension(30, 20));

        txtPHFloracion.setEditable(false);
        txtPHFloracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPHFloracion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtPHFloracion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtPHFloracion.setPreferredSize(new java.awt.Dimension(30, 20));

        javax.swing.GroupLayout pnlFloracionLayout = new javax.swing.GroupLayout(pnlFloracion);
        pnlFloracion.setLayout(pnlFloracionLayout);
        pnlFloracionLayout.setHorizontalGroup(
            pnlFloracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFloracionLayout.createSequentialGroup()
                .addGroup(pnlFloracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHumedadRFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFloracionLayout.createSequentialGroup()
                        .addComponent(lblDiasFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiasFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHumedadSFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFloracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFloracionLayout.createSequentialGroup()
                        .addComponent(txtHumedadSFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lblTemperaturaFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTemperaturaFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(pnlFloracionLayout.createSequentialGroup()
                        .addComponent(txtHumedadRFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lblPHFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPHFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFloracionLayout.setVerticalGroup(
            pnlFloracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFloracionLayout.createSequentialGroup()
                .addGroup(pnlFloracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiasFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiasFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHumedadSFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHumedadSFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(lblTemperaturaFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperaturaFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(pnlFloracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHumedadRFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHumedadRFolracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(lblPHFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPHFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFructificacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fructificacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lblDiasFructificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDiasFructificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiasFructificacion.setText("Dias:");
        lblDiasFructificacion.setMaximumSize(new java.awt.Dimension(40, 20));
        lblDiasFructificacion.setMinimumSize(new java.awt.Dimension(40, 20));
        lblDiasFructificacion.setPreferredSize(new java.awt.Dimension(40, 20));

        txtDesarrollo4.setEditable(false);
        txtDesarrollo4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDesarrollo4.setMaximumSize(new java.awt.Dimension(30, 20));
        txtDesarrollo4.setMinimumSize(new java.awt.Dimension(30, 20));
        txtDesarrollo4.setPreferredSize(new java.awt.Dimension(30, 20));

        lblHumedadSFructificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHumedadSFructificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHumedadSFructificacion.setText("Humedad Suelo:");
        lblHumedadSFructificacion.setMaximumSize(new java.awt.Dimension(100, 20));
        lblHumedadSFructificacion.setMinimumSize(new java.awt.Dimension(100, 20));
        lblHumedadSFructificacion.setPreferredSize(new java.awt.Dimension(100, 20));

        txtHumedadSFructificacion.setEditable(false);
        txtHumedadSFructificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHumedadSFructificacion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtHumedadSFructificacion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtHumedadSFructificacion.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("%");

        lblTemperaturaFructificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTemperaturaFructificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTemperaturaFructificacion.setText("Temperatura:");
        lblTemperaturaFructificacion.setMaximumSize(new java.awt.Dimension(100, 20));
        lblTemperaturaFructificacion.setMinimumSize(new java.awt.Dimension(100, 20));
        lblTemperaturaFructificacion.setPreferredSize(new java.awt.Dimension(100, 20));

        txtTemperaturaFructificacion.setEditable(false);
        txtTemperaturaFructificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTemperaturaFructificacion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtTemperaturaFructificacion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtTemperaturaFructificacion.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("°C");

        lblHumedadRFructificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHumedadRFructificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHumedadRFructificacion.setText("Humedad Relativa:");
        lblHumedadRFructificacion.setMaximumSize(new java.awt.Dimension(115, 20));
        lblHumedadRFructificacion.setMinimumSize(new java.awt.Dimension(115, 20));
        lblHumedadRFructificacion.setPreferredSize(new java.awt.Dimension(115, 20));

        txtHumedadRFructificacion.setEditable(false);
        txtHumedadRFructificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHumedadRFructificacion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtHumedadRFructificacion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtHumedadRFructificacion.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("%");

        lblPHFructificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPHFructificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPHFructificacion.setText("PH:");
        lblPHFructificacion.setMaximumSize(new java.awt.Dimension(30, 20));
        lblPHFructificacion.setMinimumSize(new java.awt.Dimension(30, 20));
        lblPHFructificacion.setPreferredSize(new java.awt.Dimension(30, 20));

        txtPHFructificacion.setEditable(false);
        txtPHFructificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPHFructificacion.setMaximumSize(new java.awt.Dimension(30, 20));
        txtPHFructificacion.setMinimumSize(new java.awt.Dimension(30, 20));
        txtPHFructificacion.setPreferredSize(new java.awt.Dimension(30, 20));

        javax.swing.GroupLayout pnlFructificacionLayout = new javax.swing.GroupLayout(pnlFructificacion);
        pnlFructificacion.setLayout(pnlFructificacionLayout);
        pnlFructificacionLayout.setHorizontalGroup(
            pnlFructificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFructificacionLayout.createSequentialGroup()
                .addGroup(pnlFructificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHumedadRFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFructificacionLayout.createSequentialGroup()
                        .addComponent(lblDiasFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDesarrollo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHumedadSFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFructificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFructificacionLayout.createSequentialGroup()
                        .addComponent(txtHumedadSFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(lblTemperaturaFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTemperaturaFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(pnlFructificacionLayout.createSequentialGroup()
                        .addComponent(txtHumedadRFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(lblPHFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPHFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFructificacionLayout.setVerticalGroup(
            pnlFructificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFructificacionLayout.createSequentialGroup()
                .addGroup(pnlFructificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiasFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesarrollo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHumedadSFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHumedadSFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(lblTemperaturaFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperaturaFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(pnlFructificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHumedadRFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHumedadRFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(lblPHFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPHFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDatosIdealesLayout = new javax.swing.GroupLayout(pnlDatosIdeales);
        pnlDatosIdeales.setLayout(pnlDatosIdealesLayout);
        pnlDatosIdealesLayout.setHorizontalGroup(
            pnlDatosIdealesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosIdealesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosIdealesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDesarrollo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFloracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFructificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlDatosIdealesLayout.setVerticalGroup(
            pnlDatosIdealesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosIdealesLayout.createSequentialGroup()
                .addComponent(pnlDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFloracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFructificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatosReales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Reales ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        pnlDatosReales.setMaximumSize(new java.awt.Dimension(580, 485));
        pnlDatosReales.setMinimumSize(new java.awt.Dimension(580, 485));
        pnlDatosReales.setPreferredSize(new java.awt.Dimension(580, 485));

        lblEtapaCultivo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEtapaCultivo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEtapaCultivo.setText("Etapa Cultivo:");

        txtEtapaCultivo.setEditable(false);
        txtEtapaCultivo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEtapaCultivo.setMaximumSize(new java.awt.Dimension(150, 20));
        txtEtapaCultivo.setMinimumSize(new java.awt.Dimension(150, 20));
        txtEtapaCultivo.setPreferredSize(new java.awt.Dimension(150, 20));

        lblDiasTranscurrido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDiasTranscurrido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiasTranscurrido.setText("Dias Transcurridos:");

        txtDiasTranscurridos.setEditable(false);
        txtDiasTranscurridos.setMaximumSize(new java.awt.Dimension(70, 20));
        txtDiasTranscurridos.setMinimumSize(new java.awt.Dimension(70, 20));
        txtDiasTranscurridos.setPreferredSize(new java.awt.Dimension(70, 20));

        lblHumedadSDesarrollo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHumedadSDesarrollo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHumedadSDesarrollo1.setText("Humedad Suelo:");
        lblHumedadSDesarrollo1.setMaximumSize(new java.awt.Dimension(100, 20));
        lblHumedadSDesarrollo1.setMinimumSize(new java.awt.Dimension(100, 20));
        lblHumedadSDesarrollo1.setPreferredSize(new java.awt.Dimension(100, 20));

        txtHumedadSDesarrollo1.setEditable(false);
        txtHumedadSDesarrollo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHumedadSDesarrollo1.setMaximumSize(new java.awt.Dimension(30, 20));
        txtHumedadSDesarrollo1.setMinimumSize(new java.awt.Dimension(30, 20));
        txtHumedadSDesarrollo1.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("%");

        lblTemperaturaDesarrollo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTemperaturaDesarrollo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTemperaturaDesarrollo1.setText("Temperatura:");
        lblTemperaturaDesarrollo1.setMaximumSize(new java.awt.Dimension(100, 20));
        lblTemperaturaDesarrollo1.setMinimumSize(new java.awt.Dimension(100, 20));
        lblTemperaturaDesarrollo1.setPreferredSize(new java.awt.Dimension(100, 20));

        txtTemperaturaDesarrollo1.setEditable(false);
        txtTemperaturaDesarrollo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTemperaturaDesarrollo1.setMaximumSize(new java.awt.Dimension(30, 20));
        txtTemperaturaDesarrollo1.setMinimumSize(new java.awt.Dimension(30, 20));
        txtTemperaturaDesarrollo1.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("°C");

        txtPHDesarrollo1.setEditable(false);
        txtPHDesarrollo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPHDesarrollo1.setMaximumSize(new java.awt.Dimension(30, 20));
        txtPHDesarrollo1.setMinimumSize(new java.awt.Dimension(30, 20));
        txtPHDesarrollo1.setPreferredSize(new java.awt.Dimension(30, 20));

        lblPHDesarrollo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPHDesarrollo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPHDesarrollo1.setText("PH:");
        lblPHDesarrollo1.setMaximumSize(new java.awt.Dimension(30, 20));
        lblPHDesarrollo1.setMinimumSize(new java.awt.Dimension(30, 20));
        lblPHDesarrollo1.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("%");

        txtHumedadRDesarrollo1.setEditable(false);
        txtHumedadRDesarrollo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHumedadRDesarrollo1.setMaximumSize(new java.awt.Dimension(30, 20));
        txtHumedadRDesarrollo1.setMinimumSize(new java.awt.Dimension(30, 20));
        txtHumedadRDesarrollo1.setPreferredSize(new java.awt.Dimension(30, 20));

        lblHumedadRDesarrollo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHumedadRDesarrollo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHumedadRDesarrollo1.setText("Humedad Relativa:");
        lblHumedadRDesarrollo1.setMaximumSize(new java.awt.Dimension(115, 20));
        lblHumedadRDesarrollo1.setMinimumSize(new java.awt.Dimension(115, 20));
        lblHumedadRDesarrollo1.setPreferredSize(new java.awt.Dimension(115, 20));

        javax.swing.GroupLayout pnlDatosRealesLayout = new javax.swing.GroupLayout(pnlDatosReales);
        pnlDatosReales.setLayout(pnlDatosRealesLayout);
        pnlDatosRealesLayout.setHorizontalGroup(
            pnlDatosRealesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosRealesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosRealesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosRealesLayout.createSequentialGroup()
                        .addComponent(lblEtapaCultivo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEtapaCultivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDiasTranscurrido, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiasTranscurridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosRealesLayout.createSequentialGroup()
                        .addGroup(pnlDatosRealesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblHumedadSDesarrollo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTemperaturaDesarrollo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnlDatosRealesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosRealesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTemperaturaDesarrollo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosRealesLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtHumedadSDesarrollo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(lblHumedadRDesarrollo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHumedadRDesarrollo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(lblPHDesarrollo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPHDesarrollo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosRealesLayout.setVerticalGroup(
            pnlDatosRealesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosRealesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosRealesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEtapaCultivo)
                    .addComponent(txtEtapaCultivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiasTranscurrido)
                    .addComponent(txtDiasTranscurridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosRealesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHumedadSDesarrollo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHumedadSDesarrollo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(lblHumedadRDesarrollo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHumedadRDesarrollo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(lblPHDesarrollo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPHDesarrollo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosRealesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperaturaDesarrollo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperaturaDesarrollo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control Riego", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlCultivosLayout = new javax.swing.GroupLayout(pnlCultivos);
        pnlCultivos.setLayout(pnlCultivosLayout);
        pnlCultivosLayout.setHorizontalGroup(
            pnlCultivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCultivosLayout.createSequentialGroup()
                .addContainerGap(496, Short.MAX_VALUE)
                .addGroup(pnlCultivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatosReales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(pnlCultivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCultivosLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addGroup(pnlCultivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlDatosCultivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlDatosIdeales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(506, Short.MAX_VALUE)))
        );
        pnlCultivosLayout.setVerticalGroup(
            pnlCultivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCultivosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosReales, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlCultivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCultivosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlDatosCultivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pnlDatosIdeales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlDatosCultivo.getAccessibleContext().setAccessibleParent(pnlCultivos);
        pnlDatosIdeales.getAccessibleContext().setAccessibleParent(pnlCultivos);

        jTabbedPane1.addTab("Monitoreo Cultivos", pnlCultivos);

        jmArchivo.setText("Archivo");

        jMenuItem1.setText("Nuevo Proceso Cultivo");
        jmArchivo.add(jMenuItem1);

        jMenuItem2.setText("Monitorear Proceso Cultivo");
        jmArchivo.add(jMenuItem2);

        jMenuItem6.setText("Monitorear Deposito de Agua");
        jmArchivo.add(jMenuItem6);

        jMenuBar1.add(jmArchivo);

        jMenu2.setText("Configuraciones");

        jMenuItem3.setText("Usuarios");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Lotes");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Cultivos");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Reportes");

        jMenuItem7.setText("Procesos Activos");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Procesos Terminados");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void txtNombreLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreLoteActionPerformed

    private void txtNumProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumProcesoActionPerformed

    private void txtDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionActionPerformed

    /**
     * @param args the command line arguments
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMonitoreoControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMonitoreoControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMonitoreoControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMonitoreoControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMonitoreoControl().setVisible(true);
            }
        });
    }
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JLabel lblDiasDesarrollo;
    private javax.swing.JLabel lblDiasFloracion;
    private javax.swing.JLabel lblDiasFructificacion;
    private javax.swing.JLabel lblDiasTranscurrido;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblEtapaCultivo;
    private javax.swing.JLabel lblHumedadRDesarrollo;
    private javax.swing.JLabel lblHumedadRDesarrollo1;
    private javax.swing.JLabel lblHumedadRFolracion;
    private javax.swing.JLabel lblHumedadRFructificacion;
    private javax.swing.JLabel lblHumedadSDesarrollo;
    private javax.swing.JLabel lblHumedadSDesarrollo1;
    private javax.swing.JLabel lblHumedadSFolracion;
    private javax.swing.JLabel lblHumedadSFructificacion;
    private javax.swing.JLabel lblNombreCult;
    private javax.swing.JLabel lblNombreLote;
    private javax.swing.JLabel lblNumProceso;
    private javax.swing.JLabel lblPHDesarrollo;
    private javax.swing.JLabel lblPHDesarrollo1;
    private javax.swing.JLabel lblPHFloracion;
    private javax.swing.JLabel lblPHFructificacion;
    private javax.swing.JLabel lblTemperaturaDesarrollo;
    private javax.swing.JLabel lblTemperaturaDesarrollo1;
    private javax.swing.JLabel lblTemperaturaFolracion;
    private javax.swing.JLabel lblTemperaturaFructificacion;
    private javax.swing.JPanel pnlCultivos;
    private javax.swing.JPanel pnlDatosCultivo;
    private javax.swing.JPanel pnlDatosIdeales;
    private javax.swing.JPanel pnlDatosReales;
    private javax.swing.JPanel pnlDesarrollo;
    private javax.swing.JPanel pnlFloracion;
    private javax.swing.JPanel pnlFructificacion;
    private javax.swing.JTextField txtDesarrollo;
    private javax.swing.JTextField txtDesarrollo4;
    private javax.swing.JTextField txtDiasFloracion;
    private javax.swing.JTextField txtDiasTranscurridos;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtEtapaCultivo;
    private javax.swing.JTextField txtHumedadRDesarrollo;
    private javax.swing.JTextField txtHumedadRDesarrollo1;
    private javax.swing.JTextField txtHumedadRFolracion;
    private javax.swing.JTextField txtHumedadRFructificacion;
    private javax.swing.JTextField txtHumedadSDesarrollo;
    private javax.swing.JTextField txtHumedadSDesarrollo1;
    private javax.swing.JTextField txtHumedadSFolracion;
    private javax.swing.JTextField txtHumedadSFructificacion;
    private javax.swing.JTextField txtNombreCult;
    private javax.swing.JTextField txtNombreLote;
    private javax.swing.JTextField txtNumProceso;
    private javax.swing.JTextField txtPHDesarrollo;
    private javax.swing.JTextField txtPHDesarrollo1;
    private javax.swing.JTextField txtPHFloracion;
    private javax.swing.JTextField txtPHFructificacion;
    private javax.swing.JTextField txtTemperaturaDesarrollo;
    private javax.swing.JTextField txtTemperaturaDesarrollo1;
    private javax.swing.JTextField txtTemperaturaFolracion;
    private javax.swing.JTextField txtTemperaturaFructificacion;
    // End of variables declaration//GEN-END:variables
}
