/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author HP 240
 */
public class frmPrincipal extends javax.swing.JFrame {
    //Las siguientes variables son necesarias para poder cambiar la interfaz grafica de la ventana principal.
    private UIManager.LookAndFeelInfo[] apariencias;
    private Dimension dim;
    private int ancho = 0, alto = 0;

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        //Con esta linea cargamos los diseños instalados en nuestro sistema operativo.
        apariencias = UIManager.getInstalledLookAndFeels();
        //En las dos lineas siguientes envoco los metodos para asignar las apariencia y ajustar la ventana.
        this.cambiarApariencia(3);
        this.ajustarVentana();
    }
    // Con este metodo ajustamos la apariencia visuales del entorno.    
    public void cambiarApariencia(int item){
        
        try {
            UIManager.setLookAndFeel(this.apariencias[item].getClassName());
            SwingUtilities.updateComponentTreeUI(this);
            String s1 = this.apariencias[item].getClassName();
            this.getContentPane().setBackground(new Color(240, 240, 240));
            
            //this.txtUsuario.setText(this.usuario.getNombre());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }
    // En este metodo ajustaremos las dimensiones del frame y los paneles de la plicacion a las dimensiones del display
    // del ordenador en el que se ejecutará.
    public void ajustarVentana(){
        //Obtengo las dimensiones del display donde se ejecutará la aplicacion y ajusto los valores.
        dim = this.getToolkit().getScreenSize();
        alto = (int) dim.getHeight() - 45;
        ancho = (int) dim.getWidth() - 3;
        dim.setSize(ancho, alto);
        //Asigno valores a las propiedades del frame para ajustar el frame a las dimensiones del display.
        this.setMinimumSize(dim);
        this.setMaximumSize(dim);
        this.setPreferredSize(dim);
        
        dim.setSize(ancho-40, alto);
        
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbHerramientas = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        pnlControlDepositoAgua = new javax.swing.JPanel();
        jpbNivelAgua = new javax.swing.JProgressBar();
        lblNivelAgua = new javax.swing.JLabel();
        lblEstadoBombaDeposito = new javax.swing.JLabel();
        btnStartBombaDeposito = new javax.swing.JButton();
        btnStopBombaDeposito = new javax.swing.JButton();
        lblTextEstadoBomba = new javax.swing.JLabel();
        lblControlManualDeposito = new javax.swing.JLabel();
        pnlControlRiego = new javax.swing.JPanel();
        pnlGraficas = new javax.swing.JPanel();
        pnlInfoLotes = new javax.swing.JPanel();
        pnlTablaDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jmbMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 760));
        setMinimumSize(new java.awt.Dimension(1200, 760));
        setPreferredSize(new java.awt.Dimension(1200, 760));
        setResizable(false);

        jtbHerramientas.setRollover(true);
        jtbHerramientas.setMaximumSize(new java.awt.Dimension(1200, 30));
        jtbHerramientas.setMinimumSize(new java.awt.Dimension(1200, 30));
        jtbHerramientas.setPreferredSize(new java.awt.Dimension(1200, 30));

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbHerramientas.add(jButton1);

        pnlControlDepositoAgua.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control Deposito Agua", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 153, 0))); // NOI18N
        pnlControlDepositoAgua.setMaximumSize(new java.awt.Dimension(500, 200));
        pnlControlDepositoAgua.setMinimumSize(new java.awt.Dimension(500, 200));
        pnlControlDepositoAgua.setOpaque(false);
        pnlControlDepositoAgua.setPreferredSize(new java.awt.Dimension(500, 200));

        jpbNivelAgua.setMaximumSize(new java.awt.Dimension(70, 130));
        jpbNivelAgua.setMinimumSize(new java.awt.Dimension(70, 130));
        jpbNivelAgua.setPreferredSize(new java.awt.Dimension(70, 130));

        lblNivelAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNivelAgua.setText("Nivel Agua");

        lblEstadoBombaDeposito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadoBombaDeposito.setText("bomba");
        lblEstadoBombaDeposito.setMaximumSize(new java.awt.Dimension(100, 100));
        lblEstadoBombaDeposito.setMinimumSize(new java.awt.Dimension(100, 100));
        lblEstadoBombaDeposito.setPreferredSize(new java.awt.Dimension(100, 100));

        btnStartBombaDeposito.setText("Start");
        btnStartBombaDeposito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStartBombaDeposito.setMaximumSize(new java.awt.Dimension(100, 100));
        btnStartBombaDeposito.setMinimumSize(new java.awt.Dimension(100, 100));
        btnStartBombaDeposito.setPreferredSize(new java.awt.Dimension(100, 100));

        btnStopBombaDeposito.setText("Stop");
        btnStopBombaDeposito.setMaximumSize(new java.awt.Dimension(100, 100));
        btnStopBombaDeposito.setMinimumSize(new java.awt.Dimension(100, 100));
        btnStopBombaDeposito.setPreferredSize(new java.awt.Dimension(100, 100));

        lblTextEstadoBomba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextEstadoBomba.setText("Estado Bomba");

        lblControlManualDeposito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblControlManualDeposito.setText("Control Manual Deposito Agua");

        javax.swing.GroupLayout pnlControlDepositoAguaLayout = new javax.swing.GroupLayout(pnlControlDepositoAgua);
        pnlControlDepositoAgua.setLayout(pnlControlDepositoAguaLayout);
        pnlControlDepositoAguaLayout.setHorizontalGroup(
            pnlControlDepositoAguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlDepositoAguaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlDepositoAguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlControlDepositoAguaLayout.createSequentialGroup()
                        .addComponent(jpbNivelAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstadoBombaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlControlDepositoAguaLayout.createSequentialGroup()
                        .addComponent(lblNivelAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTextEstadoBomba, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlControlDepositoAguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlControlDepositoAguaLayout.createSequentialGroup()
                        .addComponent(btnStartBombaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStopBombaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblControlManualDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlControlDepositoAguaLayout.setVerticalGroup(
            pnlControlDepositoAguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlDepositoAguaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlDepositoAguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadoBombaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpbNivelAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlControlDepositoAguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnStartBombaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnStopBombaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlControlDepositoAguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivelAgua)
                    .addComponent(lblTextEstadoBomba)
                    .addComponent(lblControlManualDeposito))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlControlRiego.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control Riego", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 153, 0))); // NOI18N
        pnlControlRiego.setMaximumSize(new java.awt.Dimension(500, 200));
        pnlControlRiego.setMinimumSize(new java.awt.Dimension(500, 200));
        pnlControlRiego.setPreferredSize(new java.awt.Dimension(500, 200));

        javax.swing.GroupLayout pnlControlRiegoLayout = new javax.swing.GroupLayout(pnlControlRiego);
        pnlControlRiego.setLayout(pnlControlRiegoLayout);
        pnlControlRiegoLayout.setHorizontalGroup(
            pnlControlRiegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlControlRiegoLayout.setVerticalGroup(
            pnlControlRiegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );

        pnlGraficas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graficas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 153, 0))); // NOI18N

        javax.swing.GroupLayout pnlGraficasLayout = new javax.swing.GroupLayout(pnlGraficas);
        pnlGraficas.setLayout(pnlGraficasLayout);
        pnlGraficasLayout.setHorizontalGroup(
            pnlGraficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlGraficasLayout.setVerticalGroup(
            pnlGraficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlInfoLotes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Infromacion Lotes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 153, 0))); // NOI18N
        pnlInfoLotes.setMaximumSize(new java.awt.Dimension(662, 200));
        pnlInfoLotes.setMinimumSize(new java.awt.Dimension(662, 200));
        pnlInfoLotes.setPreferredSize(new java.awt.Dimension(662, 200));

        javax.swing.GroupLayout pnlInfoLotesLayout = new javax.swing.GroupLayout(pnlInfoLotes);
        pnlInfoLotes.setLayout(pnlInfoLotesLayout);
        pnlInfoLotesLayout.setHorizontalGroup(
            pnlInfoLotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlInfoLotesLayout.setVerticalGroup(
            pnlInfoLotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );

        pnlTablaDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Cultivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 153, 0))); // NOI18N
        pnlTablaDatos.setMaximumSize(new java.awt.Dimension(662, 474));
        pnlTablaDatos.setMinimumSize(new java.awt.Dimension(662, 474));
        pnlTablaDatos.setPreferredSize(new java.awt.Dimension(662, 474));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setMaximumSize(new java.awt.Dimension(650, 451));
        jTable1.setMinimumSize(new java.awt.Dimension(650, 451));
        jTable1.setPreferredSize(new java.awt.Dimension(650, 451));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnlTablaDatosLayout = new javax.swing.GroupLayout(pnlTablaDatos);
        pnlTablaDatos.setLayout(pnlTablaDatosLayout);
        pnlTablaDatosLayout.setHorizontalGroup(
            pnlTablaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        pnlTablaDatosLayout.setVerticalGroup(
            pnlTablaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jMenu1.setText("File");
        jmbMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        jmbMenuBar.add(jMenu2);

        setJMenuBar(jmbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlControlDepositoAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControlRiego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlGraficas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlInfoLotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTablaDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlInfoLotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControlDepositoAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlControlRiego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlGraficas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlTablaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartBombaDeposito;
    private javax.swing.JButton btnStopBombaDeposito;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuBar jmbMenuBar;
    private javax.swing.JProgressBar jpbNivelAgua;
    private javax.swing.JToolBar jtbHerramientas;
    private javax.swing.JLabel lblControlManualDeposito;
    private javax.swing.JLabel lblEstadoBombaDeposito;
    private javax.swing.JLabel lblNivelAgua;
    private javax.swing.JLabel lblTextEstadoBomba;
    private javax.swing.JPanel pnlControlDepositoAgua;
    private javax.swing.JPanel pnlControlRiego;
    private javax.swing.JPanel pnlGraficas;
    private javax.swing.JPanel pnlInfoLotes;
    private javax.swing.JPanel pnlTablaDatos;
    // End of variables declaration//GEN-END:variables
}
